# Site settings
title: "PyTorch KR Website"
author: "PyTorch Korea Community"
default_author: The PyTorch KR Team
description: "PyTorch Korea Community - it's an unofficial user community for Korean"
latest_version: 1.0
timezone: Asia/Seoul
url: "https://pytorch.kr"
baseurl: ""
plugins:
  - jekyll-redirect-from
  - jekyll-autoprefixer
  - jekyll-feed
sass:
  load_paths:
    - _sass
    - node_modules
exclude: [vendor, node_modules, README.md, CODE_OF_CONDUCT.md, Gemfile, Gemdile.lock, LICENSE, yarn.lock, yarn-error.log, package.json, Makefile, scripts, docs, _hub/docs/template.md]
include: [_static, _images, _modules, _sources, _tensor_str.html, _utils.html]
keep_files: [vendor/assets, docs/master/_static/js/vendor/]
github: [metadata]
external_urls:
  org: https://pytorch.org
  org_docs: https://pytorch.org/docs
  org_tutorials: https://pytorch.org/tutorials
  hub_template: https://github.com/pytorch/hub/blob/master/docs/template.md
  previous_pytorch_versions: https://pytorch.kr/previous-versions/
  hub_issue: https://github.com/9bow/PyTorch-hub-kr/issues
  www_issue: https://github.com/9bow/PyTorchKR/issues
  community: https://discuss.pytorch.kr
  tutorials: https://tutorials.pytorch.kr/
  tutorials_github: https://github.com/9bow/PyTorch-tutorials-kr
livereload: false
markdown: kramdown
highlighter: rouge
collections:
  about:
    output: true
  get_started:
    output: true
  ecosystem:
    output: false
    permalink: /ecosystem/:path/
  hub:
    output: true
    permalink: /hub/:title/
  resources:
    output: false
  features:
    output: true
  courses:
    output: false
  mobile:
    output: true
  news:
    output: true
